// The ledger of the Durable treatment when its second attempt is rejected (case
// `ac012-summary-includes-all-four`, plan: targeted timeout, then a rejection): one successful
// transaction, generated by the WP-09 golden builder. That single transaction contradicts the initial
// hypothesis that both treatment variants create two (spec "Initial Hypothesis", AC-RUA-012).

import type { Uuid4 } from '../../../../src/record-contract/primitives.ts';
import type { ProcessingTerminalReason } from '../../../../src/record-contract/records/group-b/vocabulary.ts';

export const HYPOTHESIS_CONTRADICTING_TRANSACTIONS: readonly Uuid4[] = [
  'd7c9907a-9f36-45e3-9cf2-bc6906f7eae5' as Uuid4,
];

/**
 * The rejected second attempt ends the request with PROVIDER_REJECTED (BR-RUA-022). The single
 * transaction still passes, but BR-RUA-030 gives `correct_completion = true` "only when
 * preservation_verdict = pass and processing_terminal_reason = SUCCEEDED", so it is `false` here.
 */
export const HYPOTHESIS_CONTRADICTING_TERMINAL_REASON: ProcessingTerminalReason = 'PROVIDER_REJECTED';
