// The run package the study-comparison golden cases start from: the harness base
// `run-durable-treatment` (all four canonical trials, design §12.4) plus the files the trial and
// closure phases freeze after it: each trial's oracle result, the late-evidence assessment, the
// cleanup result, the leak audit, the safety assessment, the source provenance and the coordination
// journal. Every digest is a fixture link (`@sha256(path)`), so it is the digest of the stored bytes
// whatever an operation changes. Case files compose these operations and state their expectations
// from the spec.

import type { JsonValue, Sha256Hex, Uuid4, UtcMillis } from '../../../../src/record-contract/primitives.ts';
import type { SourceProvenance } from '../../../../src/record-contract/records/group-a/source_provenance.ts';
import type { LeaseEventRecorded } from '../../../../src/record-contract/records/group-b/lease_event_recorded.ts';
import type { LeaseEvent } from '../../../../src/record-contract/records/group-b/vocabulary.ts';
import type { CleanupResult } from '../../../../src/record-contract/records/group-c/cleanup_result.ts';
import type { LateEvidenceAssessment } from '../../../../src/record-contract/records/group-c/late_evidence_assessment.ts';
import type {
  LeakAuditResult,
  LeakedResource,
} from '../../../../src/record-contract/records/group-c/leak_audit_result.ts';
import type { SafetyAssessment } from '../../../../src/record-contract/records/group-c/safety_assessment.ts';
import type { StudyRecord } from '../../../../src/record-contract/records/index.ts';
import { EXECUTION_PATHS, PACKAGE_LAYOUT } from '../../../../src/evidence-package/package-layout.ts';
import type { FourDeclaredTrials } from '../../../../src/study-comparison/run-summary.ts';
import { linkSha256 } from '../../../support/golden-builder/digest-links.ts';
import type { ScenarioOperation } from '../../../support/golden-builder/operation-parsing.ts';
import { validOracleResult } from './oracle-results.ts';

function uuid(text: string): Uuid4 {
  return text as Uuid4;
}

/** The base run (`test/golden/_harness/fixtures/base-run-durable-treatment`). */
export const RUN_ID = uuid('b42ee7a8-4b45-43d7-8ca3-cb72ceae84c4');

/** The four declared trials of the base manifest, in BR-RUA-019 order. */
export const RUN_TRIALS: FourDeclaredTrials = [
  {
    sequence: 1,
    trial_id: uuid('d1d0a2b9-d331-4919-a5e0-44819414b6e9'),
    variant_id: 'conventional',
    scenario: 'CONTROL',
  },
  { sequence: 2, trial_id: uuid('af5fd7e2-4950-41df-baea-6ae3a692a869'), variant_id: 'durable', scenario: 'CONTROL' },
  {
    sequence: 3,
    trial_id: uuid('1549b47d-5c04-4f8c-98f1-789a4dc2eda2'),
    variant_id: 'conventional',
    scenario: 'COMMIT_THEN_TIMEOUT',
  },
  {
    sequence: 4,
    trial_id: uuid('1e8c8347-0a1f-473d-8ad2-453d867f8804'),
    variant_id: 'durable',
    scenario: 'COMMIT_THEN_TIMEOUT',
  },
];

/**
 * The successful transactions each base trial's ledger snapshot holds (generated by the WP-09 golden
 * builder): one per CONTROL trial and two per treatment trial, the configured trace of the spec.
 */
export const BASE_TRANSACTIONS: readonly (readonly Uuid4[])[] = [
  [uuid('45330d17-68f2-490e-a631-e1f052952dda')],
  [uuid('ae7855bd-6732-4962-988d-a45feefdd7d2')],
  [uuid('00c37040-7e90-468a-ae4c-4154e2256e84'), uuid('0b20928c-038b-464c-9e66-b27b33a88465')],
  [uuid('3ada1bbc-7422-422d-a83b-c11c12ea7e1a'), uuid('d7c9907a-9f36-45e3-9cf2-bc6906f7eae5')],
];

/** The qualification and source values the base manifest froze (BR-RUA-028, BR-RUA-042). */
export const BASE_QUALIFICATION = {
  qualification: {
    transport_probe_id: uuid('2559d5f6-ec95-4777-a74e-452fcfde7526'),
    original_package_index_sha256: '0ce79e7b162dfbfe009ad3c8fd6845b2df8cf7e849dc5a4ef9d36bffc51af141' as Sha256Hex,
  },
  transport_scope_snapshot_sha256: '8b028ecfcbb3fec4ae6ed54d1a5025427d7eba14d5f9c31bc66ab17e44b0738e' as Sha256Hex,
} as const;

const MANIFEST_DIGEST = linkSha256(EXECUTION_PATHS.executionManifest);
const RUN_CORRELATION = { run_id: RUN_ID, execution_manifest_sha256: MANIFEST_DIGEST } as const;
const LEASE_INSTANCE = uuid('7d1c3e0a-5b6f-4c2d-9e8a-1f0b2c3d4e5f');
const ADMISSION_ATTEMPT_ID = uuid('8151c8f7-bc90-4f2e-8bc3-020e31c4090d');

const at = (text: string): UtcMillis => text as UtcMillis;

/** What a case varies in the closure the base run reaches. */
export interface ClosureSpec {
  readonly cleanup_status: 'succeeded' | 'failed';
  readonly leaks: readonly LeakedResource[];
  /** The last lease event the coordination journal records (design §10.3 finalize). */
  readonly final_lease_event: Extract<LeaseEvent, 'RELEASED' | 'RECOVERY_REQUIRED'>;
}

/** The clean closure of AC-RUA-027: cleanup succeeded, audit clean, lease released. */
export const CLEAN_CLOSURE: ClosureSpec = { cleanup_status: 'succeeded', leaks: [], final_lease_event: 'RELEASED' };

/**
 * Every operation that turns the base into a frozen, closed run package.
 *
 * @example
 * defineGoldenCase({ ..., base: 'run-durable-treatment', operations: frozenRunOperations(BASE_TRANSACTIONS, CLEAN_CLOSURE) });
 */
export function frozenRunOperations(
  transactions: readonly (readonly Uuid4[])[],
  closure: ClosureSpec,
): readonly ScenarioOperation[] {
  return [
    ...oracleResultOperations(transactions),
    putJson(EXECUTION_PATHS.sourceProvenance, sourceProvenance()),
    // The manifest pins the provenance by digest (BR-RUA-042); linking keeps the pin exact.
    {
      op: 'set',
      path: EXECUTION_PATHS.executionManifest,
      pointer: '/source/source_provenance_sha256',
      value: linkSha256(EXECUTION_PATHS.sourceProvenance),
    },
    putJson(EXECUTION_PATHS.lateEvidenceAssessment, quietLateEvidence()),
    putJson(EXECUTION_PATHS.cleanupResult, cleanupResult(closure.cleanup_status)),
    putJson(EXECUTION_PATHS.leakAuditResult, leakAudit(closure.leaks)),
    putJson(EXECUTION_PATHS.safetyAssessment, withinLimitsSafety()),
    {
      op: 'put_file',
      path: EXECUTION_PATHS.coordinationJournal,
      content: {
        kind: 'jsonl',
        records: [
          recordJson(leaseEvent(1, 'ACQUIRED', at('2026-10-05T12:00:00.500Z'))),
          recordJson(leaseEvent(2, closure.final_lease_event, at('2026-10-05T13:14:00.000Z'))),
        ],
      },
    },
  ];
}

/**
 * The oracle result of each declared trial, judged on the given ledger transactions.
 *
 * @example
 * oracleResultOperations(BASE_TRANSACTIONS); // four put_file operations
 */
export function oracleResultOperations(transactions: readonly (readonly Uuid4[])[]): readonly ScenarioOperation[] {
  return RUN_TRIALS.map((trial, index) => {
    const unit = { kind: 'trial', trial_id: trial.trial_id } as const;
    const result = validOracleResult({
      run_id: RUN_ID,
      trial,
      execution_manifest_sha256: MANIFEST_DIGEST,
      trial_manifest_sha256: linkSha256(PACKAGE_LAYOUT.unitFile(unit, 'trialManifest')),
      provider_transaction_ids: transactions[index] ?? [],
      digest_of: linkSha256,
      checked_at: at('2026-10-05T12:56:00.000Z'),
    });
    return putJson(PACKAGE_LAYOUT.unitFile(unit, 'oracleResult'), result);
  });
}

/**
 * A leaked resource of the given D-30 capability class.
 *
 * @example
 * leakedResource('storage_only'); // the source queue, still observed
 */
export function leakedResource(capability: 'storage_only' | 'processing_capable'): LeakedResource {
  return capability === 'storage_only'
    ? {
        resource_type: 'AWS::SQS::Queue',
        identifier: 'suc1-b42ee7a8-durable-source.fifo',
        surface: 'queues',
        capability_class: 'storage_only',
        ownership_basis: 'resource_manifest_and_tags',
      }
    : {
        resource_type: 'AWS::Lambda::EventSourceMapping',
        identifier: '0d6f4c2e-8a1b-4d3c-9e7f-5a6b7c8d9e0f',
        surface: 'event_source_mappings',
        capability_class: 'processing_capable',
        ownership_basis: 'recorded_stack',
      };
}

function putJson(path: string, record: StudyRecord): ScenarioOperation {
  return { op: 'put_file', path, content: { kind: 'json', record: recordJson(record) } };
}

// Typed records are JSON by construction; their interfaces only lack an index signature.
function recordJson(record: StudyRecord): JsonValue {
  return record as unknown as JsonValue;
}

function sourceProvenance(): SourceProvenance {
  return {
    schema_version: 1,
    record_type: 'source_provenance',
    admission_attempt_id: ADMISSION_ATTEMPT_ID,
    commit_sha: 'e5a024c47b5a19c9ddd6497a9ca4d22ce283929d',
    tree_sha: 'c22a336fefa22200ed067efb08ab3391f09cea08',
    detached_head: false,
    branch: 'feature/rua-study-1',
    clean_confirmed: true,
    lockfile_path: 'package-lock.json',
    lockfile_sha256: '4d73dc9811c4c605f57672d26da794796874bb038bd665f04f8866bfc0595600' as Sha256Hex,
    tool_versions: { node: 'v24.15.0', npm: '11.6.0' },
    recorded_at: at('2026-10-05T11:59:00.000Z'),
  };
}

function quietLateEvidence(): LateEvidenceAssessment {
  return {
    schema_version: 1,
    record_type: 'late_evidence_assessment',
    ...RUN_CORRELATION,
    late_evidence_status: 'none',
    monitoring: 'complete',
    monitoring_started_at: at('2026-10-05T12:55:00.000Z'),
    monitoring_ended_at: at('2026-10-05T13:05:00.000Z'),
    correlated_record_count: 0,
    reassessments: RUN_TRIALS.map((trial) => {
      const path = PACKAGE_LAYOUT.unitFile({ kind: 'trial', trial_id: trial.trial_id }, 'oracleResult');
      return {
        frozen_result_ref: { artifact_path: path, artifact_sha256: linkSha256(path) },
        trial_id: trial.trial_id,
        status: 'none',
        changes: [],
      };
    }),
    reasons: [],
    evidence_refs: [
      { artifact_path: EXECUTION_PATHS.runnerJournal, artifact_sha256: linkSha256(EXECUTION_PATHS.runnerJournal) },
    ],
    assessed_at: at('2026-10-05T13:05:01.000Z'),
  };
}

function cleanupResult(status: 'succeeded' | 'failed'): CleanupResult {
  const failed = status === 'failed';
  return {
    schema_version: 1,
    record_type: 'cleanup_result',
    ...RUN_CORRELATION,
    cleanup_mode: 'NORMAL',
    cleanup_status: status,
    steps: [
      {
        step: 9,
        status: failed ? 'failed' : 'succeeded',
        started_at: at('2026-10-05T13:06:00.000Z'),
        completed_at: at('2026-10-05T13:10:00.000Z'),
        reasons: failed
          ? [
              {
                code: 'STACK_DELETE_FAILED',
                subject: 'SucRua-run-b42ee7a8',
                detail: 'stack deletion ended DELETE_FAILED; expected DELETE_COMPLETE',
              },
            ]
          : [],
      },
    ],
    resources: [],
    stopped_durable_execution_arns: [],
    deleted_dlq_message_ids: [],
    duration_breach: false,
    started_at: at('2026-10-05T13:05:30.000Z'),
    completed_at: at('2026-10-05T13:10:00.000Z'),
  };
}

function leakAudit(leaks: readonly LeakedResource[]): LeakAuditResult {
  const pass = (start: string, end: string): LeakAuditResult['passes'][number] => ({
    started_at: at(start),
    completed_at: at(end),
    surfaces: [
      { surface: 'tag_index', query_ok: true, observed: leaks.map((leak) => leak.identifier) },
      { surface: 'functions', query_ok: true, observed: [] },
    ],
  });
  return {
    schema_version: 1,
    record_type: 'leak_audit_result',
    ...RUN_CORRELATION,
    leak_audit_status: leaks.length === 0 ? 'clean' : 'leaks_detected',
    passes: [
      pass('2026-10-05T13:10:30.000Z', '2026-10-05T13:10:40.000Z'),
      pass('2026-10-05T13:12:40.000Z', '2026-10-05T13:12:50.000Z'),
    ],
    leaks,
    ambiguous: [],
    stable_absence_interval_ms: leaks.length === 0 ? 120_000 : 0,
    audited_at: at('2026-10-05T13:12:50.000Z'),
  };
}

function withinLimitsSafety(): SafetyAssessment {
  return {
    schema_version: 1,
    record_type: 'safety_assessment',
    ...RUN_CORRELATION,
    safety_status: 'within_limits',
    checks: [
      {
        boundary: 'ACTIVE_TIME',
        declared_limit: '4500000 ms',
        observed: '3300000 ms',
        result: 'within_limits',
        evidence_refs: [
          { artifact_path: EXECUTION_PATHS.runnerJournal, artifact_sha256: linkSha256(EXECUTION_PATHS.runnerJournal) },
        ],
        checked_at: at('2026-10-05T13:13:00.000Z'),
      },
    ],
    reasons: [],
    assessed_at: at('2026-10-05T13:13:00.000Z'),
  };
}

function leaseEvent(sequence: number, event: LeaseEvent, occurredAt: UtcMillis): LeaseEventRecorded {
  return {
    schema_version: 1,
    record_type: 'lease_event_recorded',
    event_id: uuid(`6a0e5b4c-3d2f-4e1a-8b9c-0d1e2f3a4b5${String(sequence)}`),
    ...RUN_CORRELATION,
    occurred_at: occurredAt,
    source: 'coordination_lease',
    source_instance_id: LEASE_INSTANCE,
    source_sequence: sequence,
    lease_event: event,
    owner_kind: 'RUN',
    owner_id: RUN_ID,
    owner_manifest_sha256: MANIFEST_DIGEST,
  };
}
