// Deterministic values of the golden scenario builder (design §12.4, WP-09). Golden fixture bytes
// are generated once, committed and regenerated byte for byte by `--check`, so nothing here reads
// a clock, a random source or the environment: identities are digests of readable labels and
// instants are offsets on one fixed timeline. Business values are the spec's reference tables
// (OR-RUA-001 financial fixture, OR-RUA-002 timing, OR-RUA-003..005 safety).

import { createHash } from 'node:crypto';

import type { MoneyDecimal, Sha256Hex, Uuid4, UtcMillis } from '../../../src/record-contract/primitives.ts';
import { formatUtcMillis } from '../../../src/record-contract/timestamps.ts';

/** 2026-10-05T12:00:00.000Z: instant zero of every golden timeline. */
export const TIMELINE_ORIGIN_MS = Date.UTC(2026, 9, 5, 12, 0, 0, 0);

/** OR-RUA-001: the one captured payment and its full approved refund. */
export const FINANCIAL_FIXTURE = {
  currency: 'BRL',
  payment_id: 'pay-poc-001',
  captured_amount_minor: 10000,
  refund_request_id: 'ref-poc-001',
  approved_amount_minor: 10000,
  decision: 'APPROVED',
} as const;

/** OR-RUA-002 values the builder's timelines use, in milliseconds. */
export const GOLDEN_TIMING = {
  provider_client_deadline_ms: 3000,
  provider_safety_release_ms: 15000,
  conventional_visibility_timeout_ms: 60000,
  durable_visibility_timeout_ms: 360000,
  durable_retry_delay_ms: 60000,
  max_receive_count: 2,
  observation_deadline_ms: 600000,
  stabilization_interval_ms: 120000,
  queue_poll_interval_ms: 30000,
  treatment_poll_interval_ms: 250,
} as const;

/** The study account and Region every golden execution runs in (OR-RUA-003: `us-east-1`). */
export const GOLDEN_ACCOUNT_ID = '012345678901';
export const GOLDEN_REGION = 'us-east-1';

/** The immutable provider version every golden caller targets (BR-RUA-053). */
export const GOLDEN_PROVIDER_VERSION = '1';

/** The caller function version recorded by the variants' executions. */
export const GOLDEN_CALLER_VERSION = '1';

/**
 * A lowercase UUIDv4 derived from a label: the SHA-256 of the label with the version nibble set
 * to 4 and the variant nibble to 8-b. Equal labels give equal ids and distinct labels distinct
 * ids, so fixtures never depend on generation order.
 *
 * @example
 * goldenUuid('run'); // the same lowercase UUIDv4 on every call
 */
export function goldenUuid(label: string): Uuid4 {
  const hex = createHash('sha256').update(`golden-builder/uuid/${label}`).digest('hex');
  const variant = '89ab'.charAt(Number.parseInt(hex.charAt(16), 16) % 4);
  // Lowercase hex in the 8-4-4-4-12 layout with version 4 and variant 8-b is a UUIDv4 by
  // construction; the golden-builder fuzz suite checks it with the kernel's isUuid4 for any label.
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-4${hex.slice(13, 16)}-${variant}${hex.slice(17, 20)}-${hex.slice(20, 32)}` as Uuid4;
}

/**
 * A SHA-256 digest standing for bytes the fixture does not carry, such as the deployment
 * assembly a manifest names. Each label gives its own digest.
 *
 * @example
 * labelDigest('deployment-assembly-inventory'); // 64 lowercase hex characters
 */
export function labelDigest(label: string): Sha256Hex {
  return createHash('sha256').update(`golden-builder/digest/${label}`).digest('hex') as Sha256Hex;
}

/**
 * The millisecond UTC instant `offsetMs` after the timeline origin.
 *
 * @example
 * instantAt(1500); // '2026-10-05T12:00:01.500Z'
 */
export function instantAt(offsetMs: number): UtcMillis {
  if (!Number.isSafeInteger(offsetMs) || offsetMs < 0) {
    throw new RangeError(`timeline offset ${String(offsetMs)} ms; expected a nonnegative safe integer`);
  }
  return formatUtcMillis(new Date(TIMELINE_ORIGIN_MS + offsetMs));
}

/**
 * A USD amount as the `money_decimal` string the manifests carry.
 *
 * @example
 * usd('5.00'); // '5.00'
 */
export function usd(amount: `${number}.${number}`): MoneyDecimal {
  return amount as MoneyDecimal;
}
